[build]
command = "npm run build:debug"
publish = ".next"
node_version = "18"

[build.environment]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
OPENAI_API_KEY = ""
NODE_OPTIONS = "--max-old-space-size=4096"

# Disable secrets scanning for public environment variables
[build.processing.secrets]
scan = true
SECRETS_SCAN_OMIT_KEYS = [
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
]

# Optimize caching for Next.js
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Handle Next.js image optimization
[[redirects]]
from = "/_next/image"
to = "/.netlify/images"
status = 200
query = { url = ":url", w = ":width", q = ":quality" }

[[plugins]]
package = "@netlify/plugin-nextjs"
